### ISSUE TITLE
No i2c-hid-core.c patchfile found for kernel version 6.6

### ISSUE THREAD

**Issue by forcebook** [hacklian/lenovo_82yu_i2c_hid-dkms#1]
lenovo_82yu_i2c_hid-dkms-master]# ./build.sh --kernel-version 6.6
[INFO] Running dependency check...
  > [INFO] Dependency 'sudo' is fulfilled!
  > [INFO] Dependency 'uname' is fulfilled!
  > [INFO] Dependency 'cat' is fulfilled!
  > [INFO] Dependency 'dmidecode' is fulfilled!
  > [INFO] Dependency 'wget' is fulfilled!
  > [INFO] Dependency 'bc' is fulfilled!
  > [INFO] Dependency 'sed' is fulfilled!
[INFO] Running compatibility check...
  > [INFO] System Vendor (LENOVO) is compatible!
  > [INFO] System Vendor (82YU) is compatible!
  > [DONE] Kernel Version: 6.6
[INFO] Creating Workdir...
  > [DONE] Workdir '/tmp/i2c-hid-dkms' created!
[INFO] Downloading linux kernel files from repository...
  > [DONE] Downloaded i2c-hid-core.c!
  > [DONE] Downloaded i2c-hid-dmi-quirks.c!
  > [DONE] Downloaded i2c-hid.h!
  > [DONE] Downloaded hid-ids.h!
[INFO] Patching downloaded kernel files...
  > [INFO] No i2c-hid-core.c patchfile found for kernel version 6.6, trying generic patchfile...
  > [ERROR] Could not patch i2c-hid-core.c! Aborting...

**Comment by hacklian** [comment]
As per the README, the module was not yet tested with Kernel 6.6 and from your error message it seems that it's not compatibile and will require a modified patch. I will try to do that once the kernel update hits my machine.

**Comment by hacklian** [comment]
In the meantime, if you want to try or are able to, you can see the differences between the files in the `/src/patch/6.1/` directory. You could try to create your own patch for 6.6 based on that.

**Comment by hacklian** [comment]
Just installed Kernel `6.6.8` (mine is the arch linux version) today and the touchpad and keyboard is working natively without the need for kernel or DSDT patching!  I would recommend you update to this version.

**Comment by hacklian** [comment]
Apparently it is fixed with Kernel Version `>=6.6.1` and `>=6.5.10`!
I still use the LTS Kernel so that's why it took some time for me to get the news.
